# theme = "gruvbox"
theme = "gruvbox_light"

[editor]
line-number = "relative"
mouse = false
middle-click-paste = true
cursorline = true
color-modes = true
scrolloff = 19
rulers = [120]
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator","file-encoding"]
center = ["file-name", "file-modification-indicator"]
right =  ["diagnostics", "selections", "position", "position-percentage", "total-line-numbers"]
separator = "|"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "all"
tab = "all"

[keys.normal]
"C-l" = [":write", ":run-shell-command make | tee ~/.myfifo"]

[keys.insert]
"C-[" = "normal_mode"
"S-ret" = "open_below"
